import React from 'react';
import { Button, Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, useDisclosure, Spinner } from "@heroui/react";
import { ShieldCheckIcon } from '@heroicons/react/24/outline';
import { motion } from 'framer-motion';

export default function BiasAnalysis({ article }) {
  const [biasAnalysis, setBiasAnalysis] = React.useState(null);
  const [isAnalyzing, setIsAnalyzing] = React.useState(false);
  const [hasAnalyzed, setHasAnalyzed] = React.useState(false);
  const { isOpen, onOpen, onClose } = useDisclosure();

  const handleBiasAnalysis = async () => {
    if (hasAnalyzed && biasAnalysis) {
      onOpen();
      return;
    }

    setIsAnalyzing(true);
    
    try {
      const response = await fetch('/api/analyze-news', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ newsId: article.id }),
      });

      const data = await response.json();
      
      if (data.success) {
        setBiasAnalysis(data.analysis);
        setHasAnalyzed(true);
      } else {
        setBiasAnalysis(`Error: ${data.error || 'Failed to analyze article'}`);
      }
    } catch (error) {
      setBiasAnalysis(`Error: Failed to connect to analysis service`);
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Auto-start analysis when component mounts
  React.useEffect(() => {
    if (article && article.id && !hasAnalyzed && !isAnalyzing) {
      handleBiasAnalysis();
    }
  }, [article]);

  const openModal = () => {
    onOpen();
    // If analysis isn't done yet and modal is opened, show the loading state
  };

  const reAnalyze = () => {
    setBiasAnalysis(null);
    setHasAnalyzed(false);
    handleBiasAnalysis();
  };

  return (
    <>
      {/* Bias Analysis Button - Fixed Position */}
      <motion.div 
        className="fixed right-12 top-[40%] z-30"
        initial={{ opacity: 0, x: 50 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.6, delay: 1.6 }}
      >
        <Button
          color="secondary"
          variant="shadow"
          size="lg"
          onClick={openModal}
          className="rounded-full px-4 py-2 flex items-center gap-2 text-purple-700 bg-purple-50 hover:bg-purple-100 relative"
        >
          <ShieldCheckIcon className="w-5 h-5" />
          <span className="hidden sm:inline">Bias Check</span>
          {isAnalyzing && (
            <div className="absolute -top-1 -right-1 w-3 h-3 bg-blue-500 rounded-full animate-pulse"></div>
          )}
          {hasAnalyzed && !isAnalyzing && (
            <div className="absolute -top-1 -right-1 w-3 h-3 bg-green-500 rounded-full"></div>
          )}
        </Button>
      </motion.div>

      {/* Bias Analysis Modal */}
      <Modal 
        isOpen={isOpen} 
        onClose={onClose}
        size="3xl"
        scrollBehavior="inside"
        className="max-h-[80vh]"
      >
        <ModalContent>
          <ModalHeader className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <ShieldCheckIcon className="w-6 h-6 text-purple-600" />
              <span>Bias Analysis Report</span>
              {isAnalyzing && (
                <Spinner size="sm" color="primary" />
              )}
            </div>
            <p className="text-sm text-gray-600 font-normal">
              AI-powered analysis of "{article.title}"
            </p>
          </ModalHeader>
          <ModalBody>
            {isAnalyzing ? (
              <div className="flex flex-col items-center justify-center py-12">
                <Spinner size="lg" color="primary" className="mb-4" />
                <p className="text-gray-600">Analyzing article for bias and perspective...</p>
                <p className="text-sm text-gray-500 mt-2">This analysis started when you loaded the page</p>
              </div>
            ) : biasAnalysis ? (
              <div className="space-y-4">
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <p className="text-sm text-yellow-800">
                    <strong>Disclaimer:</strong> This analysis is generated by AI and should be used as a starting point for critical thinking, not as absolute truth.
                  </p>
                </div>
                <div className="prose prose-sm max-w-none">
                  <pre className="whitespace-pre-wrap font-sans text-gray-800 leading-relaxed">
                    {biasAnalysis}
                  </pre>
                </div>
              </div>
            ) : (
              <div className="text-center py-8">
                <p className="text-gray-600">Starting analysis...</p>
              </div>
            )}
          </ModalBody>
          <ModalFooter>
            <Button color="danger" variant="light" onPress={onClose}>
              Close
            </Button>
            {biasAnalysis && !isAnalyzing && (
              <Button 
                color="primary" 
                onPress={reAnalyze}
              >
                Re-analyze
              </Button>
            )}
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
} 